server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Arquivos do TELEMAC - volume
    location /data/ {
        alias /usr/share/nginx/html/data/;
        default_type application/json;
        autoindex off;
        add_header Cache-Control "public, max-age=3600, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Compressão
    gzip on;
    gzip_types application/json application/geo+json text/plain application/javascript text/css;
    gzip_min_length 1024;
    gzip_comp_level 6;
    gzip_vary on;
}