server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Arquivos do TELEMAC - volume
    location /data/ {
        alias /usr/share/nginx/html/data/;
        autoindex off;
        add_header Cache-Control "no-cache";
    }

    
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Compressão para os GeoJSON 
    gzip on;
    gzip_types application/json application/geo+json text/plain;
    gzip_min_length 1024;
}